project:
  type: website
  output-dir: docs

website:
  title: "CGED PVA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - population.qmd
      - parameters.qmd
      - model.qmd
      - validation.qmd
      - base_model.qmd
      - scenarios.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
execute: 
  cache: false
editor: visual

