project:
  type: website

website:
  title: "CGED PVA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - population.qmd
      - parameters.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
execute: 
  cache: false
editor: visual

